FROM golang:1.23-alpine
ENV GOCACHE=/go/cache
RUN mkdir -p /go/cache && chown 1000:1000 /go/cache

WORKDIR /backend
RUN chown -R 1000:1000 /backend
USER 1000
COPY ./go.mod ./go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o server ./index.go
EXPOSE 8080
CMD ["./server"]